"""Bundled instrument universe.

S&P 500 + major ETFs/indexes/crypto/forex/EU names. Frozen list so we don't
hit a network during search. Refresh via `scripts/refresh_universe.py`
(or extend by reading a CSV).
"""
from __future__ import annotations

# Format: (symbol, name, exchange, asset_class, sector)
SP500: list[tuple[str, str, str, str, str | None]] = [
    ("AAPL", "Apple Inc.", "NASDAQ", "stock", "Technology"),
    ("MSFT", "Microsoft Corporation", "NASDAQ", "stock", "Technology"),
    ("NVDA", "NVIDIA Corporation", "NASDAQ", "stock", "Technology"),
    ("GOOGL", "Alphabet Inc. Class A", "NASDAQ", "stock", "Communication Services"),
    ("GOOG", "Alphabet Inc. Class C", "NASDAQ", "stock", "Communication Services"),
    ("AMZN", "Amazon.com, Inc.", "NASDAQ", "stock", "Consumer Cyclical"),
    ("META", "Meta Platforms, Inc.", "NASDAQ", "stock", "Communication Services"),
    ("TSLA", "Tesla, Inc.", "NASDAQ", "stock", "Consumer Cyclical"),
    ("BRK-B", "Berkshire Hathaway Class B", "NYSE", "stock", "Financial Services"),
    ("AVGO", "Broadcom Inc.", "NASDAQ", "stock", "Technology"),
    ("LLY", "Eli Lilly and Company", "NYSE", "stock", "Healthcare"),
    ("JPM", "JPMorgan Chase & Co.", "NYSE", "stock", "Financial Services"),
    ("V", "Visa Inc.", "NYSE", "stock", "Financial Services"),
    ("UNH", "UnitedHealth Group", "NYSE", "stock", "Healthcare"),
    ("XOM", "Exxon Mobil Corporation", "NYSE", "stock", "Energy"),
    ("WMT", "Walmart Inc.", "NYSE", "stock", "Consumer Defensive"),
    ("MA", "Mastercard Inc.", "NYSE", "stock", "Financial Services"),
    ("JNJ", "Johnson & Johnson", "NYSE", "stock", "Healthcare"),
    ("PG", "Procter & Gamble", "NYSE", "stock", "Consumer Defensive"),
    ("ORCL", "Oracle Corporation", "NYSE", "stock", "Technology"),
    ("HD", "The Home Depot", "NYSE", "stock", "Consumer Cyclical"),
    ("COST", "Costco Wholesale", "NASDAQ", "stock", "Consumer Defensive"),
    ("ABBV", "AbbVie Inc.", "NYSE", "stock", "Healthcare"),
    ("BAC", "Bank of America Corp.", "NYSE", "stock", "Financial Services"),
    ("KO", "The Coca-Cola Company", "NYSE", "stock", "Consumer Defensive"),
    ("CVX", "Chevron Corporation", "NYSE", "stock", "Energy"),
    ("AMD", "Advanced Micro Devices", "NASDAQ", "stock", "Technology"),
    ("CRM", "Salesforce, Inc.", "NYSE", "stock", "Technology"),
    ("MRK", "Merck & Co.", "NYSE", "stock", "Healthcare"),
    ("PEP", "PepsiCo, Inc.", "NASDAQ", "stock", "Consumer Defensive"),
    ("ADBE", "Adobe Inc.", "NASDAQ", "stock", "Technology"),
    ("NFLX", "Netflix, Inc.", "NASDAQ", "stock", "Communication Services"),
    ("ACN", "Accenture plc", "NYSE", "stock", "Technology"),
    ("LIN", "Linde plc", "NASDAQ", "stock", "Basic Materials"),
    ("MCD", "McDonald's Corporation", "NYSE", "stock", "Consumer Cyclical"),
    ("CSCO", "Cisco Systems", "NASDAQ", "stock", "Technology"),
    ("TMO", "Thermo Fisher Scientific", "NYSE", "stock", "Healthcare"),
    ("ABT", "Abbott Laboratories", "NYSE", "stock", "Healthcare"),
    ("WFC", "Wells Fargo & Company", "NYSE", "stock", "Financial Services"),
    ("DIS", "The Walt Disney Company", "NYSE", "stock", "Communication Services"),
    ("DHR", "Danaher Corporation", "NYSE", "stock", "Healthcare"),
    ("VZ", "Verizon Communications", "NYSE", "stock", "Communication Services"),
    ("INTC", "Intel Corporation", "NASDAQ", "stock", "Technology"),
    ("CMCSA", "Comcast Corporation", "NASDAQ", "stock", "Communication Services"),
    ("INTU", "Intuit Inc.", "NASDAQ", "stock", "Technology"),
    ("TXN", "Texas Instruments", "NASDAQ", "stock", "Technology"),
    ("AMGN", "Amgen Inc.", "NASDAQ", "stock", "Healthcare"),
    ("QCOM", "QUALCOMM Incorporated", "NASDAQ", "stock", "Technology"),
    ("IBM", "International Business Machines", "NYSE", "stock", "Technology"),
    ("NEE", "NextEra Energy", "NYSE", "stock", "Utilities"),
    ("PM", "Philip Morris International", "NYSE", "stock", "Consumer Defensive"),
    ("PFE", "Pfizer Inc.", "NYSE", "stock", "Healthcare"),
    ("CAT", "Caterpillar Inc.", "NYSE", "stock", "Industrials"),
    ("GS", "The Goldman Sachs Group", "NYSE", "stock", "Financial Services"),
    ("RTX", "RTX Corporation", "NYSE", "stock", "Industrials"),
    ("UBER", "Uber Technologies", "NYSE", "stock", "Technology"),
    ("HON", "Honeywell International", "NASDAQ", "stock", "Industrials"),
    ("UNP", "Union Pacific Corporation", "NYSE", "stock", "Industrials"),
    ("AMAT", "Applied Materials", "NASDAQ", "stock", "Technology"),
    ("BKNG", "Booking Holdings", "NASDAQ", "stock", "Consumer Cyclical"),
    ("SPGI", "S&P Global Inc.", "NYSE", "stock", "Financial Services"),
    ("BX", "Blackstone Inc.", "NYSE", "stock", "Financial Services"),
    ("ELV", "Elevance Health", "NYSE", "stock", "Healthcare"),
    ("DE", "Deere & Company", "NYSE", "stock", "Industrials"),
    ("LMT", "Lockheed Martin", "NYSE", "stock", "Industrials"),
    ("BLK", "BlackRock, Inc.", "NYSE", "stock", "Financial Services"),
    ("BA", "The Boeing Company", "NYSE", "stock", "Industrials"),
    ("LOW", "Lowe's Companies", "NYSE", "stock", "Consumer Cyclical"),
    ("GE", "General Electric", "NYSE", "stock", "Industrials"),
    ("MDT", "Medtronic plc", "NYSE", "stock", "Healthcare"),
    ("SBUX", "Starbucks Corporation", "NASDAQ", "stock", "Consumer Cyclical"),
    ("ADP", "Automatic Data Processing", "NASDAQ", "stock", "Industrials"),
    ("MDLZ", "Mondelez International", "NASDAQ", "stock", "Consumer Defensive"),
    ("CI", "Cigna Group", "NYSE", "stock", "Healthcare"),
    ("ISRG", "Intuitive Surgical", "NASDAQ", "stock", "Healthcare"),
    ("GILD", "Gilead Sciences", "NASDAQ", "stock", "Healthcare"),
    ("MO", "Altria Group", "NYSE", "stock", "Consumer Defensive"),
    ("PLD", "Prologis, Inc.", "NYSE", "stock", "Real Estate"),
    ("REGN", "Regeneron Pharmaceuticals", "NASDAQ", "stock", "Healthcare"),
    ("VRTX", "Vertex Pharmaceuticals", "NASDAQ", "stock", "Healthcare"),
    ("PANW", "Palo Alto Networks", "NASDAQ", "stock", "Technology"),
    ("CB", "Chubb Limited", "NYSE", "stock", "Financial Services"),
    ("NOW", "ServiceNow, Inc.", "NYSE", "stock", "Technology"),
    ("BMY", "Bristol-Myers Squibb", "NYSE", "stock", "Healthcare"),
    ("MMC", "Marsh & McLennan", "NYSE", "stock", "Financial Services"),
    ("ETN", "Eaton Corporation", "NYSE", "stock", "Industrials"),
    ("SCHW", "Charles Schwab", "NYSE", "stock", "Financial Services"),
    ("T", "AT&T Inc.", "NYSE", "stock", "Communication Services"),
    ("AMT", "American Tower", "NYSE", "stock", "Real Estate"),
    ("ANET", "Arista Networks", "NYSE", "stock", "Technology"),
    ("LRCX", "Lam Research Corporation", "NASDAQ", "stock", "Technology"),
    ("SYK", "Stryker Corporation", "NYSE", "stock", "Healthcare"),
    ("C", "Citigroup Inc.", "NYSE", "stock", "Financial Services"),
    ("ZTS", "Zoetis Inc.", "NYSE", "stock", "Healthcare"),
    ("KLAC", "KLA Corporation", "NASDAQ", "stock", "Technology"),
    ("MU", "Micron Technology", "NASDAQ", "stock", "Technology"),
    ("ABNB", "Airbnb, Inc.", "NASDAQ", "stock", "Consumer Cyclical"),
    ("PYPL", "PayPal Holdings", "NASDAQ", "stock", "Financial Services"),
    ("SQ", "Block, Inc.", "NYSE", "stock", "Technology"),
    ("SHOP", "Shopify Inc.", "NYSE", "stock", "Technology"),
    ("SNOW", "Snowflake Inc.", "NYSE", "stock", "Technology"),
    ("DDOG", "Datadog, Inc.", "NASDAQ", "stock", "Technology"),
    ("CRWD", "CrowdStrike Holdings", "NASDAQ", "stock", "Technology"),
    ("ZS", "Zscaler, Inc.", "NASDAQ", "stock", "Technology"),
    ("NET", "Cloudflare, Inc.", "NYSE", "stock", "Technology"),
    ("ROKU", "Roku, Inc.", "NASDAQ", "stock", "Communication Services"),
    ("PLTR", "Palantir Technologies", "NYSE", "stock", "Technology"),
    ("COIN", "Coinbase Global", "NASDAQ", "stock", "Financial Services"),
    ("HOOD", "Robinhood Markets", "NASDAQ", "stock", "Financial Services"),
    ("RBLX", "Roblox Corporation", "NYSE", "stock", "Communication Services"),
    ("F", "Ford Motor Company", "NYSE", "stock", "Consumer Cyclical"),
    ("GM", "General Motors", "NYSE", "stock", "Consumer Cyclical"),
    ("RIVN", "Rivian Automotive", "NASDAQ", "stock", "Consumer Cyclical"),
    ("LCID", "Lucid Group", "NASDAQ", "stock", "Consumer Cyclical"),
    ("NIO", "NIO Inc.", "NYSE", "stock", "Consumer Cyclical"),
    ("XPEV", "XPeng Inc.", "NYSE", "stock", "Consumer Cyclical"),
    ("BABA", "Alibaba Group", "NYSE", "stock", "Consumer Cyclical"),
    ("JD", "JD.com, Inc.", "NASDAQ", "stock", "Consumer Cyclical"),
    ("PDD", "PDD Holdings", "NASDAQ", "stock", "Consumer Cyclical"),
    ("TSM", "Taiwan Semiconductor", "NYSE", "stock", "Technology"),
    ("NKE", "NIKE, Inc.", "NYSE", "stock", "Consumer Cyclical"),
    ("CVS", "CVS Health Corporation", "NYSE", "stock", "Healthcare"),
    ("DUK", "Duke Energy", "NYSE", "stock", "Utilities"),
    ("EOG", "EOG Resources", "NYSE", "stock", "Energy"),
    ("OXY", "Occidental Petroleum", "NYSE", "stock", "Energy"),
    ("CMG", "Chipotle Mexican Grill", "NYSE", "stock", "Consumer Cyclical"),
]

ETFS: list[tuple[str, str, str, str, str | None]] = [
    ("SPY", "SPDR S&P 500 ETF", "NYSEARCA", "etf", None),
    ("QQQ", "Invesco QQQ Trust", "NASDAQ", "etf", None),
    ("IWM", "iShares Russell 2000 ETF", "NYSEARCA", "etf", None),
    ("VTI", "Vanguard Total Stock Market ETF", "NYSEARCA", "etf", None),
    ("DIA", "SPDR Dow Jones Industrial ETF", "NYSEARCA", "etf", None),
    ("VOO", "Vanguard S&P 500 ETF", "NYSEARCA", "etf", None),
    ("VEA", "Vanguard FTSE Developed Markets ETF", "NYSEARCA", "etf", None),
    ("VWO", "Vanguard FTSE Emerging Markets ETF", "NYSEARCA", "etf", None),
    ("BND", "Vanguard Total Bond Market ETF", "NASDAQ", "etf", None),
    ("AGG", "iShares Core US Aggregate Bond ETF", "NYSEARCA", "etf", None),
    ("TLT", "iShares 20+ Year Treasury Bond ETF", "NASDAQ", "etf", None),
    ("GLD", "SPDR Gold Shares", "NYSEARCA", "etf", None),
    ("SLV", "iShares Silver Trust", "NYSEARCA", "etf", None),
    ("USO", "US Oil Fund", "NYSEARCA", "etf", None),
    ("XLE", "Energy Select Sector SPDR", "NYSEARCA", "etf", "Energy"),
    ("XLF", "Financial Select Sector SPDR", "NYSEARCA", "etf", "Financial Services"),
    ("XLK", "Technology Select Sector SPDR", "NYSEARCA", "etf", "Technology"),
    ("XLV", "Health Care Select Sector SPDR", "NYSEARCA", "etf", "Healthcare"),
    ("XLI", "Industrial Select Sector SPDR", "NYSEARCA", "etf", "Industrials"),
    ("XLP", "Consumer Staples Select Sector SPDR", "NYSEARCA", "etf", "Consumer Defensive"),
    ("XLY", "Consumer Discretionary Select Sector SPDR", "NYSEARCA", "etf", "Consumer Cyclical"),
    ("XLU", "Utilities Select Sector SPDR", "NYSEARCA", "etf", "Utilities"),
    ("XLB", "Materials Select Sector SPDR", "NYSEARCA", "etf", "Basic Materials"),
    ("XLRE", "Real Estate Select Sector SPDR", "NYSEARCA", "etf", "Real Estate"),
    ("XLC", "Communication Services Select Sector SPDR", "NYSEARCA", "etf", "Communication Services"),
    ("ARKK", "ARK Innovation ETF", "NYSEARCA", "etf", None),
    ("EEM", "iShares MSCI Emerging Markets ETF", "NYSEARCA", "etf", None),
    ("EFA", "iShares MSCI EAFE ETF", "NYSEARCA", "etf", None),
    ("HYG", "iShares iBoxx High Yield Corporate Bond ETF", "NYSEARCA", "etf", None),
    ("LQD", "iShares iBoxx Investment Grade Corporate Bond ETF", "NYSEARCA", "etf", None),
]

INDEXES: list[tuple[str, str, str, str, str | None]] = [
    ("^GSPC", "S&P 500 Index", "INDEX", "index", None),
    ("^IXIC", "Nasdaq Composite", "INDEX", "index", None),
    ("^DJI", "Dow Jones Industrial Average", "INDEX", "index", None),
    ("^VIX", "CBOE Volatility Index", "INDEX", "index", None),
    ("^RUT", "Russell 2000", "INDEX", "index", None),
    ("^FTSE", "FTSE 100", "INDEX", "index", None),
    ("^GDAXI", "DAX Performance Index", "INDEX", "index", None),
    ("^FCHI", "CAC 40", "INDEX", "index", None),
    ("^N225", "Nikkei 225", "INDEX", "index", None),
    ("^HSI", "Hang Seng Index", "INDEX", "index", None),
    ("^STOXX50E", "EURO STOXX 50", "INDEX", "index", None),
]

CRYPTO: list[tuple[str, str, str, str, str | None]] = [
    ("BTC-USD", "Bitcoin USD", "CCC", "crypto", None),
    ("ETH-USD", "Ethereum USD", "CCC", "crypto", None),
    ("SOL-USD", "Solana USD", "CCC", "crypto", None),
    ("BNB-USD", "BNB USD", "CCC", "crypto", None),
    ("XRP-USD", "XRP USD", "CCC", "crypto", None),
    ("ADA-USD", "Cardano USD", "CCC", "crypto", None),
    ("DOGE-USD", "Dogecoin USD", "CCC", "crypto", None),
    ("AVAX-USD", "Avalanche USD", "CCC", "crypto", None),
    ("MATIC-USD", "Polygon USD", "CCC", "crypto", None),
    ("LINK-USD", "Chainlink USD", "CCC", "crypto", None),
]

FOREX: list[tuple[str, str, str, str, str | None]] = [
    ("EURUSD=X", "EUR / USD", "FX", "forex", None),
    ("GBPUSD=X", "GBP / USD", "FX", "forex", None),
    ("USDJPY=X", "USD / JPY", "FX", "forex", None),
    ("AUDUSD=X", "AUD / USD", "FX", "forex", None),
    ("USDCHF=X", "USD / CHF", "FX", "forex", None),
    ("USDCAD=X", "USD / CAD", "FX", "forex", None),
    ("EURGBP=X", "EUR / GBP", "FX", "forex", None),
    ("DX-Y.NYB", "US Dollar Index", "FX", "forex", None),
]

EU_STOCKS: list[tuple[str, str, str, str, str | None]] = [
    ("ASML.AS", "ASML Holding", "AMS", "stock", "Technology"),
    ("SAP.DE", "SAP SE", "XETRA", "stock", "Technology"),
    ("MC.PA", "LVMH Moët Hennessy Louis Vuitton", "PAR", "stock", "Consumer Cyclical"),
    ("NESN.SW", "Nestlé SA", "SWX", "stock", "Consumer Defensive"),
    ("HSBA.L", "HSBC Holdings plc", "LSE", "stock", "Financial Services"),
    ("AIR.PA", "Airbus SE", "PAR", "stock", "Industrials"),
    ("OR.PA", "L'Oréal SA", "PAR", "stock", "Consumer Defensive"),
    ("ROG.SW", "Roche Holding AG", "SWX", "stock", "Healthcare"),
    ("NOVN.SW", "Novartis AG", "SWX", "stock", "Healthcare"),
    ("SHEL.L", "Shell plc", "LSE", "stock", "Energy"),
    ("AZN.L", "AstraZeneca PLC", "LSE", "stock", "Healthcare"),
    ("RIO.L", "Rio Tinto Group", "LSE", "stock", "Basic Materials"),
    ("BP.L", "BP p.l.c.", "LSE", "stock", "Energy"),
    ("ULVR.L", "Unilever PLC", "LSE", "stock", "Consumer Defensive"),
    ("VOW3.DE", "Volkswagen AG", "XETRA", "stock", "Consumer Cyclical"),
    ("BMW.DE", "Bayerische Motoren Werke AG", "XETRA", "stock", "Consumer Cyclical"),
    ("ALV.DE", "Allianz SE", "XETRA", "stock", "Financial Services"),
    ("SIE.DE", "Siemens AG", "XETRA", "stock", "Industrials"),
    ("BAS.DE", "BASF SE", "XETRA", "stock", "Basic Materials"),
    ("ENGI.PA", "Engie SA", "PAR", "stock", "Utilities"),
]


# Curated small/mid-cap pool — heavy on biotech, fintech, EV/clean-tech, and
# beaten-down growth where the opportunity engine actually finds catalyst plays.
# These don't dilute the S&P500 list because the screeners filter by market cap;
# they expand the pool the underpriced_movers + catalyst_plays strategies scan.
SMALL_MID_CAPS: list[tuple[str, str, str, str, str | None]] = [
    # Biotech / health-tech (where most FDA catalysts surface)
    ("FEMY", "Femasys Inc.",                    "NASDAQ", "stock", "Healthcare"),
    ("VKTX", "Viking Therapeutics",             "NASDAQ", "stock", "Healthcare"),
    ("CRSP", "CRISPR Therapeutics",             "NASDAQ", "stock", "Healthcare"),
    ("BEAM", "Beam Therapeutics",               "NASDAQ", "stock", "Healthcare"),
    ("NTLA", "Intellia Therapeutics",           "NASDAQ", "stock", "Healthcare"),
    ("ARWR", "Arrowhead Pharmaceuticals",       "NASDAQ", "stock", "Healthcare"),
    ("RVMD", "Revolution Medicines",            "NASDAQ", "stock", "Healthcare"),
    ("CYTK", "Cytokinetics",                    "NASDAQ", "stock", "Healthcare"),
    ("ALNY", "Alnylam Pharmaceuticals",         "NASDAQ", "stock", "Healthcare"),
    ("EXAS", "Exact Sciences",                  "NASDAQ", "stock", "Healthcare"),
    ("TDOC", "Teladoc Health",                  "NYSE",   "stock", "Healthcare"),
    ("VEEV", "Veeva Systems",                   "NYSE",   "stock", "Healthcare"),
    # Fintech / payments
    ("AFRM", "Affirm Holdings",                 "NASDAQ", "stock", "Financial Services"),
    ("SOFI", "SoFi Technologies",               "NASDAQ", "stock", "Financial Services"),
    ("UPST", "Upstart Holdings",                "NASDAQ", "stock", "Financial Services"),
    ("HOOD", "Robinhood Markets",               "NASDAQ", "stock", "Financial Services"),
    ("LMND", "Lemonade Inc.",                   "NYSE",   "stock", "Financial Services"),
    ("OPEN", "Opendoor Technologies",           "NASDAQ", "stock", "Real Estate"),
    # EV / clean-tech
    ("RIVN", "Rivian Automotive",               "NASDAQ", "stock", "Consumer Cyclical"),
    ("LCID", "Lucid Group",                     "NASDAQ", "stock", "Consumer Cyclical"),
    ("CHPT", "ChargePoint Holdings",            "NYSE",   "stock", "Industrials"),
    ("PLUG", "Plug Power",                      "NASDAQ", "stock", "Industrials"),
    ("FCEL", "FuelCell Energy",                 "NASDAQ", "stock", "Industrials"),
    ("RUN",  "Sunrun",                          "NASDAQ", "stock", "Industrials"),
    ("ENPH", "Enphase Energy",                  "NASDAQ", "stock", "Technology"),
    ("FSLR", "First Solar",                     "NASDAQ", "stock", "Technology"),
    # Software/SaaS — out of S&P 500 or smaller cap
    ("PATH", "UiPath",                          "NYSE",   "stock", "Technology"),
    ("ESTC", "Elastic N.V.",                    "NYSE",   "stock", "Technology"),
    ("FROG", "JFrog",                           "NASDAQ", "stock", "Technology"),
    ("SEMR", "SEMrush Holdings",                "NYSE",   "stock", "Technology"),
    ("BAND", "Bandwidth Inc.",                  "NASDAQ", "stock", "Technology"),
    ("APPS", "Digital Turbine",                 "NASDAQ", "stock", "Technology"),
    ("MGNI", "Magnite",                         "NASDAQ", "stock", "Communication Services"),
    # Consumer / e-commerce
    ("RVLV", "Revolve Group",                   "NYSE",   "stock", "Consumer Cyclical"),
    ("YETI", "YETI Holdings",                   "NYSE",   "stock", "Consumer Cyclical"),
    ("CHWY", "Chewy",                           "NYSE",   "stock", "Consumer Cyclical"),
    ("CVNA", "Carvana",                         "NYSE",   "stock", "Consumer Cyclical"),
    ("FIGS", "FIGS Inc.",                       "NYSE",   "stock", "Consumer Cyclical"),
    # Misc — momentum / news-driven
    ("RKLB", "Rocket Lab USA",                  "NASDAQ", "stock", "Industrials"),
    ("ASTS", "AST SpaceMobile",                 "NASDAQ", "stock", "Communication Services"),
    ("IONQ", "IonQ Inc.",                       "NYSE",   "stock", "Technology"),
    ("RGTI", "Rigetti Computing",               "NASDAQ", "stock", "Technology"),
    ("BBAI", "BigBear.ai Holdings",             "NYSE",   "stock", "Technology"),
    ("SOUN", "SoundHound AI",                   "NASDAQ", "stock", "Technology"),
    ("SMCI", "Super Micro Computer",            "NASDAQ", "stock", "Technology"),
    ("ARM",  "Arm Holdings",                    "NASDAQ", "stock", "Technology"),
    ("MSTR", "MicroStrategy",                   "NASDAQ", "stock", "Technology"),
    ("COIN", "Coinbase Global",                 "NASDAQ", "stock", "Financial Services"),
    ("RBLX", "Roblox Corporation",              "NYSE",   "stock", "Communication Services"),
    ("U",    "Unity Software",                  "NYSE",   "stock", "Technology"),
    ("DKNG", "DraftKings",                      "NASDAQ", "stock", "Consumer Cyclical"),
    ("PENN", "PENN Entertainment",              "NASDAQ", "stock", "Consumer Cyclical"),
    ("WOLF", "Wolfspeed",                       "NYSE",   "stock", "Technology"),
    ("MARA", "MARA Holdings",                   "NASDAQ", "stock", "Financial Services"),
    ("RIOT", "Riot Platforms",                  "NASDAQ", "stock", "Financial Services"),
    ("CLSK", "CleanSpark",                      "NASDAQ", "stock", "Financial Services"),
]


def all_instruments() -> list[tuple[str, str, str, str, str | None]]:
    return [*SP500, *SMALL_MID_CAPS, *ETFS, *INDEXES, *CRYPTO, *FOREX, *EU_STOCKS]
